"""Clean up all test artifacts from main.cpp"""

import re

TARGET_FILE = r"D:\codeWorks\graphicstics\graphicstuff\main.cpp"

def clean_main_cpp():
    """Remove all test artifacts and duplicates from main.cpp"""
    
    with open(TARGET_FILE, 'r', encoding='utf-8') as f:
        content = f.read()
    
    print("Original file size:", len(content), "bytes")
    print("Original line count:", len(content.splitlines()))
    
    # First pass: Remove simple single-line patterns
    simple_patterns = [
        # Test comments
        r'//\s*Before marker \d+\n',
        r'//\s*After marker \d+\n',
        r'//\s*REPLACE_ME_\d+\n',
        r'//\s*REPLACED_\w+\n',
        r'//\s*Test comment from controller\n',
        r'//\s*Planner integration test comment\n',
        r'//\s*Inserted content\n',
        r'//\s*Generated by planner\n',
        r'//\s*EXTERNAL MODIFICATION.*?(?=\n\n|\Z)',
    ]
    
    cleaned = content
    for pattern in simple_patterns:
        cleaned = re.sub(pattern, '', cleaned, flags=re.DOTALL | re.MULTILINE)
    
    # Second pass: Remove test functions by finding and removing them
    # This handles multi-line functions with nested braces
    lines = cleaned.splitlines(keepends=True)
    result_lines = []
    skip_until_brace_count = None
    brace_count = 0
    
    for line in lines:
        # Check if this line starts a test function
        if skip_until_brace_count is None:
            # List of test function name patterns
            test_patterns = [
                r'^\s*(?:void|int|float|double|bool)\s+(?:test_replace|stagnation|baseline|staging|normal_add|rewrite|planner|reuse|refine|compat|symbol|caller|undefined|graph|recursive|demo_task|validated_demo)_\w+\s*\(',
                r'^\s*void\s+\w*test\w*\s*\(',
            ]
            
            is_test_function = any(re.match(pattern, line) for pattern in test_patterns)
            
            if is_test_function:
                # Start skipping - count braces until we close the function
                skip_until_brace_count = 0
                brace_count = line.count('{') - line.count('}')
                skip_until_brace_count += brace_count
                continue
        else:
            # We're inside a test function - count braces
            brace_count = line.count('{') - line.count('}')
            skip_until_brace_count += brace_count
            
            if skip_until_brace_count <= 0:
                # Function is complete, resume normal processing
                skip_until_brace_count = None
            continue
        
        # Keep this line
        result_lines.append(line)
    
    cleaned = ''.join(result_lines)
    
    # Remove excessive blank lines (more than 2 consecutive)
    cleaned = re.sub(r'\n{3,}', '\n\n', cleaned)
    
    # Remove trailing whitespace
    lines = cleaned.splitlines()
    lines = [line.rstrip() for line in lines]
    cleaned = '\n'.join(lines)
    
    # Ensure file ends with newline
    if not cleaned.endswith('\n'):
        cleaned += '\n'
    
    print("\nCleaned file size:", len(cleaned), "bytes")
    print("Cleaned line count:", len(cleaned.splitlines()))
    print("Removed:", len(content) - len(cleaned), "bytes")
    
    # Write cleaned content
    with open(TARGET_FILE, 'w', encoding='utf-8') as f:
        f.write(cleaned)
    
    print("\nCleanup complete!")
    
    # Show what remains
    print("\nRemaining functions:")
    function_pattern = r'^\s*(?:void|int|float|double|bool|char)\s+(\w+)\s*\('
    for line in cleaned.splitlines():
        match = re.match(function_pattern, line)
        if match:
            print(f"  - {match.group(1)}")


if __name__ == "__main__":
    print("="*60)
    print("CLEANING TEST ARTIFACTS FROM main.cpp")
    print("="*60)
    
    try:
        clean_main_cpp()
    except Exception as e:
        print(f"\n✗ Error: {e}")
        import traceback
        traceback.print_exc()
        exit(1)
    
    print("\n" + "="*60)
    print("CLEANUP SUCCESSFUL")
    print("="*60)
